### ISSUE TITLE
App breaks after a few `git add` commands

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/GitShark#17]
See: https://github.com/isomorphic-git/isomorphic-git/issues/1126

**Comment by typedrat** [comment]
Okay, the bug appears to be in Android itself:

1. `isomorphic-git` calls (through the filesystem wrapper in GitShark) the `react-native-fs` implementation of `writeFile`, which (after some marshaling to native Java) is implemented [here](https://github.com/itinance/react-native-fs/blob/f2f8f4a058cd9acfbcac3b8cf1e08fa1e9b09786/android/src/main/java/com/rnfs/RNFSManager.java#L152).
2. This calls the [`getOutputStream`](https://github.com/itinance/react-native-fs/blob/f2f8f4a058cd9acfbcac3b8cf1e08fa1e9b09786/android/src/main/java/com/rnfs/RNFSManager.java#L118) method to open a stream with which to write the file.
3. `getOutputStream` calls into the built-in Android function [`ContentResolver.openOutputStream`](https://developer.android.com/reference/android/content/ContentResolver#openOutputStream(android.net.Uri,%20java.lang.String)) with a `mode` parameter of `"w"`.
4. While there is no direct documentation of the _meaning_ of the `mode` parameter for `ContentResolver.openOutputStream`, it implies through reference to [`ContentResolver.openAssetFileDescriptor`](https://developer.android.com/reference/android/content/ContentResolver#openAssetFileDescriptor(android.net.Uri,%20java.lang.String)) and, transitively, [`ContentProvider.openAssetFile`](https://developer.android.com/reference/android/content/ContentProvider#openAssetFile(android.net.Uri,%20java.lang.String)) that the `"w"` flag causes the file to be truncated and overwritten if it already exists.
5. However, in practice, rather than truncating (or, indeed, writing in append mode or throwing an error) the existing file, the result is that the new file contents are written into a buffer that contains the content of the existing file.
    1. This is obvious from the fact that, if the existing file is longer, the previous contents remain after the end of the new file's contents.
    2. ***THIS HAS POTENTIALLY SEVERE SECURITY IMPLEMENTATIONS***, as it could potentially allow secret data to not properly be deleted, or possibly, if the implementation is "correctly" incorrect, be the sign of a lurking buffer overflow if a _larger_ file does not properly _grow_ the buffer!

I will do my best to recreate in AOSP and file a bug there, as (if validated) this is a serious bug.
